services:
  test:
    build:
      context: ../../
      dockerfile: ./docker/cicd/Dockerfile
    image: goapp001-cicd:1.24.5
    container_name: goapp001-cicd
    hostname: goapp001-cicd
    volumes:
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-../..}
        target: /app
    environment:
      GOTOOLCHAIN: local
